  # Starter pipeline
  # Start with a minimal pipeline that you can customize to build and deploy your code.
  # Add steps that build, run tests, deploy, and more:
  # https://aka.ms/yaml

  trigger:
  - master

  pool:
    vmImage: ubuntu-latest

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
  - task: ArtifactoryGenericDownload@3
    inputs:
      connection: 'clouddsein'
      specSource: 'taskConfiguration'
      fileSpec: |
        {
          "files": [
            {
              "pattern": "gaja-maven-local/*",
              "target": "/tmp/",
                "recurse": "true",
                "flat": "false"
            }
          ]
        }
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      projectKey: pro2
      includeEnvVars: true
      failNoOp: true

  - task: ArtifactoryPublishBuildInfo@1
    inputs:
      artifactoryService: 'clouddsein'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      projectKey: pro2
  - task: CmdLine@2
    inputs:
      script: 'find /tmp/com/ -type d' 
      #workingDirectory: # Optional
      #failOnStderr: false # Optional

