# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: ArtifactoryGenericDownload@3
  inputs:
    connection: 'jy_prd'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "jana-local-maven/at/oeamtc/gradle/*",
            "target": "/home/vsts/work/r1/a/"
          }
        ]
      }
    failNoOp: true
- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'jy_prd'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "/home/vsts/work/r1/a/*.jar",
            "target": "broad-test/"
          }
        ]
      }
    failNoOp: true

